language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t doanhuuhoa/docker-react-travis -f Dockerfile.dev .

script:
  - docker run -e CI=true doanhuuhoa/docker-react-travis npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-200571695773"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY